### PR TITLE
Update index.html, changed CDN77 Info

### PR DESCRIPTION
**Pull request by cdn77oskar**
Changed minimal payment to 99USD per year, added 100% SSD and origin shield.

### CODE REVIEW

**Comment by cdn77oskar** [comment]
BUMP! Just following up on the request.

**Comment by cdn77oskar** [comment]
Just BUMPing again, as a change took place, but for some reason without our commit..

**Comment by Affilma** [comment]
Could you please look at our commit? It's been almost two months since last update of your site and 3 months since we added this pull req. Currently the info as it is on the website does not correspond to what we actually offer..Thanks!

**Comment by cdn77oskar** [comment]
Could you please look at our commit? It's been almost two months since last update of your site and 3 months since we added this pull req. Currently the info as it is on the website does not correspond to what we actually offer..Thanks!

**Comment by cdn77oskar** [comment]
Hi, just following up after few months again, here are links to the respective pages of our features.
https://www.cdn77.com/next-generation-cdn (Origin shield)
https://www.cdn77.com/website-acceleration (100% SSD)

Let me know if you need additional info.

**Comment by betahex** [comment]
rejected: inaccurate details (e.g. pricing)

**Pull request closed without merging**
