### PR TITLE
Updated Azure CDN supported features

### PR DESCRIPTION
**Pull request by dksimpson**

### CODE REVIEW

**Comment by dksimpson** [comment]
Hi all, I've updated the comparison table to incorporate the latest features that Microsoft Azure CDN supports.

**Review by betahex — CHANGES_REQUESTED** [review]
the pricing should only include the highest prices (not the lowest)

**Comment by betahex** [comment]
I'm going to add your details in the next update (this week).

**Comment by PetrMarkovic** [comment]
Hi @betahex, I have found out that CDN77 is completely missing in comparison table. Can I add it so you can make an update?

**Pull request closed without merging**
